// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrtCYbAg8mb0hk7Fwo5UtUBDC0kEL3hqY',
    appId: '1:461836544300:web:c37a00070a6f5f0ad82489',
    messagingSenderId: '461836544300',
    projectId: 'bookingnew-e3791',
    authDomain: 'bookingnew-e3791.firebaseapp.com',
    storageBucket: 'bookingnew-e3791.firebasestorage.app',
    measurementId: 'G-Y9VVB9FDXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkZqmfCUUi10Ll-28Z5ppeyh7AihBEctY',
    appId: '1:461836544300:android:a57612b553b2b561d82489',
    messagingSenderId: '461836544300',
    projectId: 'bookingnew-e3791',
    storageBucket: 'bookingnew-e3791.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU7eQ526pnmu6f2i_x9pPUqEzMJ8NcNKQ',
    appId: '1:461836544300:ios:1acc6ddfec34251ed82489',
    messagingSenderId: '461836544300',
    projectId: 'bookingnew-e3791',
    storageBucket: 'bookingnew-e3791.firebasestorage.app',
    iosClientId:
        '461836544300-gdrassf383ki3rapvgj1k90j5hefsrhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingtop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU7eQ526pnmu6f2i_x9pPUqEzMJ8NcNKQ',
    appId: '1:461836544300:ios:1acc6ddfec34251ed82489',
    messagingSenderId: '461836544300',
    projectId: 'bookingnew-e3791',
    storageBucket: 'bookingnew-e3791.firebasestorage.app',
    iosClientId:
        '461836544300-gdrassf383ki3rapvgj1k90j5hefsrhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingtop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrtCYbAg8mb0hk7Fwo5UtUBDC0kEL3hqY',
    appId: '1:461836544300:web:cbd905f85b3b2514d82489',
    messagingSenderId: '461836544300',
    projectId: 'bookingnew-e3791',
    authDomain: 'bookingnew-e3791.firebaseapp.com',
    storageBucket: 'bookingnew-e3791.firebasestorage.app',
    measurementId: 'G-XMJN08FDX4',
  );
}
